## 1. Loading and Preprocessing (2 marks):

● Load the California Housing dataset using the fetch_california_housing function
from sklearn.

● Convert the dataset into a pandas DataFrame for easier handling. Handle
missing values (if any) and perform necessary feature scaling (e.g.,
standardization).

● Explain the preprocessing steps you performed and justify why they are
necessary for this dataset.

Import libraries

In [1]:
import numpy as np 
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Loading the dataset

In [10]:
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df["MedHouseVal"] = housing.target
df.head()

   MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  MedHouseVal
0  8.3252      41.0  6.984127  ...     37.88    -122.23        4.526
1  8.3014      21.0  6.238137  ...     37.86    -122.22        3.585
2  7.2574      52.0  8.288136  ...     37.85    -122.24        3.521
3  5.6431      52.0  5.817352  ...     37.85    -122.25        3.413
4  3.8462      52.0  6.281853  ...     37.85    -122.25        3.422

[5 rows x 9 columns]

Checking dataset

In [11]:

print("Shape of dataset:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

df.info()

Shape of dataset: (20640, 9)

Missing values:
MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

There is no null values to solve.

Separate features and target

In [12]:
X = df.drop("MedHouseVal", axis=1)
y = df["MedHouseVal"]
print("Feature shape : ", X.shape)
print("Target shape : ",y.shape)

Feature shape :  (20640, 8)
Target shape :  (20640,)

Split the data

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print("Trainingdata : ", X_train.shape)
print("Testing Dta : ",X_test.shape)

Trainingdata :  (16512, 8)
Testing Dta :  (4128, 8)

Feature scaling

In [15]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

The California Housing dataset was loaded using the fetch_california_housing() function from Scikit-learn and converted into a Pandas DataFrame. The dataset was checked for missing values, and no missing values were found.

The target variable MedHouseVal was separated from the input features. The dataset was then divided into training and testing sets using an 80:20 ratio. Feature scaling was performed using StandardScaler to standardize the input features. Scaling is important for algorithms such as Support Vector Regression because they are sensitive to differences in feature scales.

# 2. Regression Algorithm Implementation (5 marks):

● Implement the following regression algorithms:

○ Linear Regression
○ Decision Tree Regressor
○ Random Forest Regressor
○ Gradient Boosting Regressor
○ Support Vector Regressor (SVR)

● For each algorithm: Provide a brief explanation of how it works. Explain why it might be suitable for this dataset.

Importing models

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR

Linear Regression

In [17]:
le =LinearRegression()
le.fit(X_train_scaled,y_train)
le_predict = le.predict(X_test_scaled)

Linear Regression finds a linear relationship between the input features and the house price.

It provides a simple baseline for predicting house prices and helps us understand the relationship between features and the target.

Decision Tree reggression

In [24]:
dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train,y_train)
dt_pred = dt_model.predict(X_test)

A Decision Tree makes a series of decisions based on the feature values and divides the data into smaller groups to make predictions.

RandomForest REgression

In [25]:
rf_model = RandomForestRegressor(n_estimators=100,random_state=42)
rf_model.fit(X_train,y_train)
rf_predict = rf_model.predict(X_test)

Random Forest combines many decision trees and averages their predictions to produce the final prediction.
The California Housing dataset has several features and potentially complex relationships, which Random Forest can handle well.

Gradient Boosting Regressor

In [26]:
gb_model = GradientBoostingRegressor(random_state=42)

gb_model.fit(X_train, y_train)

gb_pred = gb_model.predict(X_test)

Gradient Boosting builds trees one after another, with each new tree trying to correct the errors made by the previous trees.

Support Vector Regressor (SVR)

In [27]:
svr_model = SVR()

svr_model.fit(X_train_scaled, y_train)

svr_pred = svr_model.predict(X_test_scaled)

SVR tries to find a function that predicts the target values while keeping prediction errors within a specified margin.

# 3. Model Evaluation and Comparison (2 marks):
● Evaluate the performance of each algorithm using the following metrics:

○ Mean Squared Error (MSE)
○ Mean Absolute Error (MAE)
○ R-squared Score (R2)

● Compare the results of all models and identify: The best-performing algorithm with justification and the worst-performing algorithm with reasoning.

import metrices

In [28]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [30]:
models = {
    "Linear Regression": le_predict,
    "Decision Tree": dt_pred,
    "Random Forest": rf_predict,
    "Gradient Boosting": gb_pred,
    "SVR": svr_pred
}

results = []

for name, predictions in models.items():
    mse = mean_squared_error(y_test, predictions)
    mae = mean_absolute_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)

    results.append([name, mse, mae, r2])

Comparison

In [31]:
results_df = pd.DataFrame(
    results,
    columns=["Model", "MSE", "MAE", "R2 Score"]
)

results_df

               Model       MSE       MAE  R2 Score
0  Linear Regression  0.538865  0.535317  0.588781
1      Decision Tree  0.494256  0.454171  0.622823
2      Random Forest  0.256022  0.327731  0.804624
3  Gradient Boosting  0.293997  0.371643  0.775645
4                SVR  0.924592  0.740147  0.294425

### Model Comparison

The models were evaluated using Mean Squared Error (MSE), Mean Absolute Error (MAE), and R² Score. Lower MSE and MAE values indicate better performance, while a higher R² score indicates better performance.

The Random Forest Regressor performed best among the tested models. It achieved the lowest MSE of **0.256022** and the lowest MAE of 0.327731. It also achieved the highest R² score of **0.804624**. Therefore, based on these evaluation metrics, Random Forest gave the strongest performance on the test data.

Best-performing algorithm

Based on the above results, Random Forest Regressor has the lowest MSE (0.256022) and lowest MAE (0.327731), while also having the highest R² score (0.804624) among the five models.

Worst-Performing Algorithm

The Support Vector Regressor (SVR) had the weakest performance among the tested models. It had the highest MSE (0.924592) and MAE (0.740147), while its R² score (0.294425) was the lowest. This indicates that SVR produced larger prediction errors and explained less variation in the house prices compared with the other models.

### Conclusion

In this assignment, five regression algorithms were implemented on the California Housing dataset: Linear Regression, Decision Tree Regressor, Random Forest Regressor, Gradient Boosting Regressor, and Support Vector Regressor.

The models were evaluated using MSE, MAE, and R² Score. Among the tested models, the Random Forest Regressor achieved the lowest MSE and MAE and the highest R² Score. Therefore, it showed the strongest performance on the test dataset.

The Support Vector Regressor had the highest MSE and MAE and the lowest R² Score among the tested models. The results show that different regression algorithms can perform differently on the same dataset.